config/routes.rb
Rails.application.routes.draw do
  resources :faxes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fax.rb
class Fax < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/faxes_controller.rb
class FaxesController < ApplicationController
  before_action :set_fax, only: [:show, :edit, :update, :destroy]

  # GET /faxes
  # GET /faxes.json
  def index
    @faxes = Fax.all
  end

  # GET /faxes/1
  # GET /faxes/1.json
  def show
  end

  # GET /faxes/new
  def new
    @fax = Fax.new
  end

  # GET /faxes/1/edit
  def edit
  end

  # POST /faxes
  # POST /faxes.json
  def create
    @fax = Fax.new(fax_params)

    respond_to do |format|
      if @fax.save
        format.html { redirect_to @fax, notice: 'Fax was successfully created.' }
        format.json { render :show, status: :created, location: @fax }
      else
        format.html { render :new }
        format.json { render json: @fax.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faxes/1
  # PATCH/PUT /faxes/1.json
  def update
    respond_to do |format|
      if @fax.update(fax_params)
        format.html { redirect_to @fax, notice: 'Fax was successfully updated.' }
        format.json { render :show, status: :ok, location: @fax }
      else
        format.html { render :edit }
        format.json { render json: @fax.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faxes/1
  # DELETE /faxes/1.json
  def destroy
    @fax.destroy
    respond_to do |format|
      format.html { redirect_to faxes_url, notice: 'Fax was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fax
      @fax = Fax.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fax_params
      params.fetch(:fax, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/faxes_helper.rb
module FaxesHelper
end

app/views/faxes/_form.html.erb
<%= form_with(model: fax, local: true) do |form| %>
  <% if fax.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fax.errors.count, "error") %> prohibited this fax from being saved:</h2>

      <ul>
        <% fax.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/faxes/edit.html.erb
<h1>Editing Fax</h1>

<%= render 'form', fax: @fax %>

<%= link_to 'Show', @fax %> |
<%= link_to 'Back', faxes_path %>

app/views/faxes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Faxes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @faxes.each do |fax| %>
      <tr>
        <td><%= link_to 'Show', fax %></td>
        <td><%= link_to 'Edit', edit_fax_path(fax) %></td>
        <td><%= link_to 'Destroy', fax, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fax', new_fax_path %>

app/views/faxes/new.html.erb
<h1>New Fax</h1>

<%= render 'form', fax: @fax %>

<%= link_to 'Back', faxes_path %>

app/views/faxes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_fax_path(@fax) %> |
<%= link_to 'Back', faxes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhatTheFax</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>